# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'params_range_setting_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParametersRangeSettingDialog(object):
    def setupUi(self, ParametersRangeSettingDialog):
        ParametersRangeSettingDialog.setObjectName("ParametersRangeSettingDialog")
        ParametersRangeSettingDialog.resize(640, 480)
        self.widget = QtWidgets.QWidget(ParametersRangeSettingDialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 621, 461))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_d = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_d.setFont(font)
        self.groupBox_d.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_d.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_d.setObjectName("groupBox_d")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_d)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 601, 116))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_tau_from = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tau_from.setFont(font)
        self.label_tau_from.setObjectName("label_tau_from")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_tau_from)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_tau_from = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_tau_from.setFont(font)
        self.lineEdit_tau_from.setObjectName("lineEdit_tau_from")
        self.horizontalLayout.addWidget(self.lineEdit_tau_from)
        self.label_tau_to = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tau_to.setFont(font)
        self.label_tau_to.setObjectName("label_tau_to")
        self.horizontalLayout.addWidget(self.label_tau_to)
        self.lineEdit_tau_to = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_tau_to.setFont(font)
        self.lineEdit_tau_to.setObjectName("lineEdit_tau_to")
        self.horizontalLayout.addWidget(self.lineEdit_tau_to)
        self.label_tau_unit = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tau_unit.setFont(font)
        self.label_tau_unit.setObjectName("label_tau_unit")
        self.horizontalLayout.addWidget(self.label_tau_unit)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_epsilon_inf_from = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_epsilon_inf_from.setFont(font)
        self.label_epsilon_inf_from.setObjectName("label_epsilon_inf_from")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_epsilon_inf_from)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_epsilon_inf_from = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_epsilon_inf_from.setFont(font)
        self.lineEdit_epsilon_inf_from.setObjectName("lineEdit_epsilon_inf_from")
        self.horizontalLayout_2.addWidget(self.lineEdit_epsilon_inf_from)
        self.label_epsilon_inf_to = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_epsilon_inf_to.setFont(font)
        self.label_epsilon_inf_to.setObjectName("label_epsilon_inf_to")
        self.horizontalLayout_2.addWidget(self.label_epsilon_inf_to)
        self.lineEdit_epsilon_inf_to = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_epsilon_inf_to.setFont(font)
        self.lineEdit_epsilon_inf_to.setObjectName("lineEdit_epsilon_inf_to")
        self.horizontalLayout_2.addWidget(self.lineEdit_epsilon_inf_to)
        self.label_epsilon_inf_unit = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_epsilon_inf_unit.setFont(font)
        self.label_epsilon_inf_unit.setObjectName("label_epsilon_inf_unit")
        self.horizontalLayout_2.addWidget(self.label_epsilon_inf_unit)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_delta_epsilon_from = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_delta_epsilon_from.setFont(font)
        self.label_delta_epsilon_from.setObjectName("label_delta_epsilon_from")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_delta_epsilon_from)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_delta_epsilon_from = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_delta_epsilon_from.setFont(font)
        self.lineEdit_delta_epsilon_from.setObjectName("lineEdit_delta_epsilon_from")
        self.horizontalLayout_3.addWidget(self.lineEdit_delta_epsilon_from)
        self.label_delta_epsilon_to = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_delta_epsilon_to.setFont(font)
        self.label_delta_epsilon_to.setObjectName("label_delta_epsilon_to")
        self.horizontalLayout_3.addWidget(self.label_delta_epsilon_to)
        self.lineEdit_delta_epsilon_to = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_delta_epsilon_to.setFont(font)
        self.lineEdit_delta_epsilon_to.setObjectName("lineEdit_delta_epsilon_to")
        self.horizontalLayout_3.addWidget(self.lineEdit_delta_epsilon_to)
        self.label_delta_epsilon_unit = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_delta_epsilon_unit.setFont(font)
        self.label_delta_epsilon_unit.setObjectName("label_delta_epsilon_unit")
        self.horizontalLayout_3.addWidget(self.label_delta_epsilon_unit)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.pushButton_d_apply = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_d_apply.setFont(font)
        self.pushButton_d_apply.setObjectName("pushButton_d_apply")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_d_apply)
        self.verticalLayout.addWidget(self.groupBox_d)
        self.groupBox_m = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_m.setFont(font)
        self.groupBox_m.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_m.setObjectName("groupBox_m")
        self.verticalLayout.addWidget(self.groupBox_m)
        self.groupBox_f = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_f.setFont(font)
        self.groupBox_f.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_f.setObjectName("groupBox_f")
        self.verticalLayout.addWidget(self.groupBox_f)

        self.retranslateUi(ParametersRangeSettingDialog)
        QtCore.QMetaObject.connectSlotsByName(ParametersRangeSettingDialog)

    def retranslateUi(self, ParametersRangeSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        ParametersRangeSettingDialog.setWindowTitle(_translate("ParametersRangeSettingDialog", "ParametersRangeSetting"))
        self.groupBox_d.setTitle(_translate("ParametersRangeSettingDialog", "Dielectric Relaxation Parameters Setting"))
        self.label_tau_from.setText(_translate("ParametersRangeSettingDialog", "Tau FROM"))
        self.label_tau_to.setText(_translate("ParametersRangeSettingDialog", "TO"))
        self.label_tau_unit.setText(_translate("ParametersRangeSettingDialog", "(s)"))
        self.label_epsilon_inf_from.setText(_translate("ParametersRangeSettingDialog", "Epsilon_Inf FROM"))
        self.label_epsilon_inf_to.setText(_translate("ParametersRangeSettingDialog", "TO"))
        self.label_epsilon_inf_unit.setText(_translate("ParametersRangeSettingDialog", "(1)"))
        self.label_delta_epsilon_from.setText(_translate("ParametersRangeSettingDialog", "Delta_Epsilon FROM"))
        self.label_delta_epsilon_to.setText(_translate("ParametersRangeSettingDialog", "TO"))
        self.label_delta_epsilon_unit.setText(_translate("ParametersRangeSettingDialog", "(1)"))
        self.pushButton_d_apply.setText(_translate("ParametersRangeSettingDialog", "APPLY!!!"))
        self.groupBox_m.setTitle(_translate("ParametersRangeSettingDialog", "Magnetization Parameters Setting"))
        self.groupBox_f.setTitle(_translate("ParametersRangeSettingDialog", "Faraday Parameters Setting"))
