# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulator_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(628, 473)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/simulator.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GroupBox_step1 = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupBox_step1.setGeometry(QtCore.QRect(10, 90, 311, 151))
        self.GroupBox_step1.setAutoFillBackground(True)
        self.GroupBox_step1.setObjectName("GroupBox_step1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.GroupBox_step1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 142))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Layout_step1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Layout_step1.setContentsMargins(0, 0, 0, 0)
        self.Layout_step1.setObjectName("Layout_step1")
        self.Layout_step1_file = QtWidgets.QHBoxLayout()
        self.Layout_step1_file.setObjectName("Layout_step1_file")
        self.PushButton_file = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PushButton_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_file.setObjectName("PushButton_file")
        self.Layout_step1_file.addWidget(self.PushButton_file)
        self.PushButton_dir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PushButton_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_dir.setObjectName("PushButton_dir")
        self.Layout_step1_file.addWidget(self.PushButton_dir)
        self.Layout_step1.addLayout(self.Layout_step1_file)
        self.ListView_file = QtWidgets.QListView(self.verticalLayoutWidget)
        self.ListView_file.setObjectName("ListView_file")
        self.Layout_step1.addWidget(self.ListView_file)
        self.Label_step1_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Label_step1_1.setObjectName("Label_step1_1")
        self.Layout_step1.addWidget(self.Label_step1_1)
        self.Label_step1_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Label_step1_2.setObjectName("Label_step1_2")
        self.Layout_step1.addWidget(self.Label_step1_2)
        self.GroupBox_step2 = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupBox_step2.setGeometry(QtCore.QRect(10, 240, 311, 181))
        self.GroupBox_step2.setAutoFillBackground(True)
        self.GroupBox_step2.setObjectName("GroupBox_step2")
        self.formLayoutWidget = QtWidgets.QWidget(self.GroupBox_step2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 20, 311, 163))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.Layout_step2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.Layout_step2.setContentsMargins(0, 0, 0, 0)
        self.Layout_step2.setObjectName("Layout_step2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(88, 0))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 92, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Layout_step2_left = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Layout_step2_left.setContentsMargins(0, 0, 0, 0)
        self.Layout_step2_left.setObjectName("Layout_step2_left")
        self.Label_alpha = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_alpha.setFont(font)
        self.Label_alpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_alpha.setObjectName("Label_alpha")
        self.Layout_step2_left.addWidget(self.Label_alpha)
        self.Label_beta = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_beta.setFont(font)
        self.Label_beta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_beta.setObjectName("Label_beta")
        self.Layout_step2_left.addWidget(self.Label_beta)
        self.Label_tau = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_tau.setFont(font)
        self.Label_tau.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_tau.setObjectName("Label_tau")
        self.Layout_step2_left.addWidget(self.Label_tau)
        self.Label_epsiloninf = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_epsiloninf.setFont(font)
        self.Label_epsiloninf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_epsiloninf.setObjectName("Label_epsiloninf")
        self.Layout_step2_left.addWidget(self.Label_epsiloninf)
        self.Label_deltaepsilon = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_deltaepsilon.setFont(font)
        self.Label_deltaepsilon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_deltaepsilon.setObjectName("Label_deltaepsilon")
        self.Layout_step2_left.addWidget(self.Label_deltaepsilon)
        self.Layout_step2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_4)
        self.Layout_step2_right = QtWidgets.QFormLayout()
        self.Layout_step2_right.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.Layout_step2_right.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.Layout_step2_right.setObjectName("Layout_step2_right")
        self.lcdNumber_alpha = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_alpha.setFont(font)
        self.lcdNumber_alpha.setSmallDecimalPoint(False)
        self.lcdNumber_alpha.setDigitCount(7)
        self.lcdNumber_alpha.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_alpha.setProperty("value", 1.0)
        self.lcdNumber_alpha.setProperty("intValue", 1)
        self.lcdNumber_alpha.setObjectName("lcdNumber_alpha")
        self.Layout_step2_right.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_alpha)
        self.lcdNumber_beta = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_beta.setFont(font)
        self.lcdNumber_beta.setDigitCount(7)
        self.lcdNumber_beta.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_beta.setProperty("value", 1.0)
        self.lcdNumber_beta.setObjectName("lcdNumber_beta")
        self.Layout_step2_right.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_beta)
        self.Slider_beta = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_beta.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_beta.setMaximum(100)
        self.Slider_beta.setSingleStep(1)
        self.Slider_beta.setPageStep(5)
        self.Slider_beta.setProperty("value", 100)
        self.Slider_beta.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_beta.setInvertedControls(False)
        self.Slider_beta.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_beta.setObjectName("Slider_beta")
        self.Layout_step2_right.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Slider_beta)
        self.lcdNumber_tau = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_tau.setFont(font)
        self.lcdNumber_tau.setSmallDecimalPoint(False)
        self.lcdNumber_tau.setDigitCount(7)
        self.lcdNumber_tau.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_tau.setProperty("value", 0.0)
        self.lcdNumber_tau.setObjectName("lcdNumber_tau")
        self.Layout_step2_right.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_tau)
        self.Slider_tau = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_tau.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_tau.setMinimum(0)
        self.Slider_tau.setMaximum(100)
        self.Slider_tau.setSingleStep(1)
        self.Slider_tau.setPageStep(2)
        self.Slider_tau.setProperty("value", 0)
        self.Slider_tau.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_tau.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_tau.setObjectName("Slider_tau")
        self.Layout_step2_right.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Slider_tau)
        self.lcdNumber_epsiloninf = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_epsiloninf.setFont(font)
        self.lcdNumber_epsiloninf.setDigitCount(7)
        self.lcdNumber_epsiloninf.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_epsiloninf.setObjectName("lcdNumber_epsiloninf")
        self.Layout_step2_right.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_epsiloninf)
        self.Slider_epsiloninf = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_epsiloninf.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_epsiloninf.setMaximum(100)
        self.Slider_epsiloninf.setPageStep(5)
        self.Slider_epsiloninf.setProperty("value", 0)
        self.Slider_epsiloninf.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_epsiloninf.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_epsiloninf.setObjectName("Slider_epsiloninf")
        self.Layout_step2_right.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Slider_epsiloninf)
        self.lcdNumber_deltaepsilon = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_deltaepsilon.setFont(font)
        self.lcdNumber_deltaepsilon.setDigitCount(7)
        self.lcdNumber_deltaepsilon.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_deltaepsilon.setObjectName("lcdNumber_deltaepsilon")
        self.Layout_step2_right.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_deltaepsilon)
        self.Slider_deltaepsilon = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_deltaepsilon.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_deltaepsilon.setMaximum(100)
        self.Slider_deltaepsilon.setSingleStep(1)
        self.Slider_deltaepsilon.setPageStep(2)
        self.Slider_deltaepsilon.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_deltaepsilon.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_deltaepsilon.setObjectName("Slider_deltaepsilon")
        self.Layout_step2_right.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Slider_deltaepsilon)
        self.Slider_alpha = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_alpha.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_alpha.setMaximum(100)
        self.Slider_alpha.setSingleStep(1)
        self.Slider_alpha.setPageStep(5)
        self.Slider_alpha.setProperty("value", 100)
        self.Slider_alpha.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_alpha.setInvertedControls(False)
        self.Slider_alpha.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_alpha.setObjectName("Slider_alpha")
        self.Layout_step2_right.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Slider_alpha)
        self.Layout_step2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.Layout_step2_right)
        self.PushButton_simulate = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton_simulate.setGeometry(QtCore.QRect(330, 100, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PushButton_simulate.setFont(font)
        self.PushButton_simulate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_simulate.setAutoDefault(False)
        self.PushButton_simulate.setDefault(False)
        self.PushButton_simulate.setFlat(False)
        self.PushButton_simulate.setObjectName("PushButton_simulate")
        self.GroupBox_step4 = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupBox_step4.setGeometry(QtCore.QRect(330, 140, 291, 291))
        self.GroupBox_step4.setAutoFillBackground(True)
        self.GroupBox_step4.setObjectName("GroupBox_step4")
        self.PushButton_plot = QtWidgets.QPushButton(self.GroupBox_step4)
        self.PushButton_plot.setGeometry(QtCore.QRect(10, 262, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PushButton_plot.setFont(font)
        self.PushButton_plot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_plot.setObjectName("PushButton_plot")
        self.ListView_results = QtWidgets.QListView(self.GroupBox_step4)
        self.ListView_results.setGeometry(QtCore.QRect(10, 20, 271, 241))
        self.ListView_results.setObjectName("ListView_results")
        self.GroupBox_title = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupBox_title.setGeometry(QtCore.QRect(20, 0, 591, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_title.sizePolicy().hasHeightForWidth())
        self.GroupBox_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.GroupBox_title.setFont(font)
        self.GroupBox_title.setStyleSheet("")
        self.GroupBox_title.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupBox_title.setObjectName("GroupBox_title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.GroupBox_title)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 571, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Layout_title = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Layout_title.setContentsMargins(0, 0, 0, 0)
        self.Layout_title.setObjectName("Layout_title")
        self.Label_fomula = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Label_fomula.setStyleSheet("image: url(:/Formula/source/formula.png);")
        self.Label_fomula.setText("")
        self.Label_fomula.setObjectName("Label_fomula")
        self.Layout_title.addWidget(self.Label_fomula)
        self.Layout_title_right = QtWidgets.QGridLayout()
        self.Layout_title_right.setObjectName("Layout_title_right")
        self.RadioButton_ccmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_ccmodel.setObjectName("RadioButton_ccmodel")
        self.Layout_title_right.addWidget(self.RadioButton_ccmodel, 1, 0, 1, 1)
        self.RadioButton_hnmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_hnmodel.setChecked(True)
        self.RadioButton_hnmodel.setObjectName("RadioButton_hnmodel")
        self.Layout_title_right.addWidget(self.RadioButton_hnmodel, 0, 0, 1, 1)
        self.RadioButton_cdmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_cdmodel.setObjectName("RadioButton_cdmodel")
        self.Layout_title_right.addWidget(self.RadioButton_cdmodel, 0, 1, 1, 1)
        self.RadioButton_dmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_dmodel.setObjectName("RadioButton_dmodel")
        self.Layout_title_right.addWidget(self.RadioButton_dmodel, 1, 1, 1, 1)
        self.Layout_title.addLayout(self.Layout_title_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 628, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSaveResultsAs = QtWidgets.QAction(MainWindow)
        self.actionSaveResultsAs.setObjectName("actionSaveResultsAs")
        self.actionParameters_Range = QtWidgets.QAction(MainWindow)
        self.actionParameters_Range.setObjectName("actionParameters_Range")
        self.menuFile.addAction(self.actionSaveResultsAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionParameters_Range)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.RadioButton_hnmodel, self.RadioButton_ccmodel)
        MainWindow.setTabOrder(self.RadioButton_ccmodel, self.RadioButton_cdmodel)
        MainWindow.setTabOrder(self.RadioButton_cdmodel, self.RadioButton_dmodel)
        MainWindow.setTabOrder(self.RadioButton_dmodel, self.PushButton_file)
        MainWindow.setTabOrder(self.PushButton_file, self.PushButton_dir)
        MainWindow.setTabOrder(self.PushButton_dir, self.ListView_file)
        MainWindow.setTabOrder(self.ListView_file, self.Slider_alpha)
        MainWindow.setTabOrder(self.Slider_alpha, self.Slider_beta)
        MainWindow.setTabOrder(self.Slider_beta, self.Slider_tau)
        MainWindow.setTabOrder(self.Slider_tau, self.Slider_epsiloninf)
        MainWindow.setTabOrder(self.Slider_epsiloninf, self.Slider_deltaepsilon)
        MainWindow.setTabOrder(self.Slider_deltaepsilon, self.PushButton_simulate)
        MainWindow.setTabOrder(self.PushButton_simulate, self.ListView_results)
        MainWindow.setTabOrder(self.ListView_results, self.PushButton_plot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulator v1.0.0.20200711_alpha by Cheng WANG, Masumoto Lab."))
        self.GroupBox_step1.setTitle(_translate("MainWindow", "STEP.1 Raw Data"))
        self.PushButton_file.setText(_translate("MainWindow", "File..."))
        self.PushButton_dir.setText(_translate("MainWindow", "Dir..."))
        self.Label_step1_1.setText(_translate("MainWindow", "*This should be the raw file from LCR meter."))
        self.Label_step1_2.setText(_translate("MainWindow", "**Filename: [serial](-DCB-[DCB]), eg. 88-8-DCB8.8"))
        self.GroupBox_step2.setTitle(_translate("MainWindow", "STEP.2 Parameters"))
        self.Label_alpha.setText(_translate("MainWindow", "Alpha: "))
        self.Label_beta.setText(_translate("MainWindow", "Beta: "))
        self.Label_tau.setText(_translate("MainWindow", "Tau: "))
        self.Label_epsiloninf.setText(_translate("MainWindow", "Epsilon_Inf: "))
        self.Label_deltaepsilon.setText(_translate("MainWindow", "Delta_Epsilon: "))
        self.PushButton_simulate.setText(_translate("MainWindow", "STEP.3 Simulate!!!"))
        self.GroupBox_step4.setTitle(_translate("MainWindow", "STEP.4 Results"))
        self.PushButton_plot.setText(_translate("MainWindow", "Plot"))
        self.GroupBox_title.setTitle(_translate("MainWindow", "Havriliak–Negami Relaxation"))
        self.RadioButton_ccmodel.setText(_translate("MainWindow", "Cole–Cole"))
        self.RadioButton_hnmodel.setText(_translate("MainWindow", "Havriliak–Negami"))
        self.RadioButton_cdmodel.setText(_translate("MainWindow", "Cole–Davidson"))
        self.RadioButton_dmodel.setText(_translate("MainWindow", "Debye"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSaveResultsAs.setText(_translate("MainWindow", "Save Results As..."))
        self.actionParameters_Range.setText(_translate("MainWindow", "Parameters Range"))
import simulator_rc
