# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulator_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/simulator.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 0, 1061, 678))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabs.setFont(font)
        self.tabs.setObjectName("tabs")
        self.tabDielectric = QtWidgets.QWidget()
        self.tabDielectric.setObjectName("tabDielectric")
        self.PushButton_simulate = QtWidgets.QPushButton(self.tabDielectric)
        self.PushButton_simulate.setGeometry(QtCore.QRect(540, 160, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_simulate.setFont(font)
        self.PushButton_simulate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_simulate.setAutoDefault(False)
        self.PushButton_simulate.setDefault(False)
        self.PushButton_simulate.setFlat(False)
        self.PushButton_simulate.setObjectName("PushButton_simulate")
        self.GroupBox_step2 = QtWidgets.QGroupBox(self.tabDielectric)
        self.GroupBox_step2.setGeometry(QtCore.QRect(10, 450, 521, 191))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step2.setFont(font)
        self.GroupBox_step2.setAutoFillBackground(True)
        self.GroupBox_step2.setObjectName("GroupBox_step2")
        self.formLayoutWidget = QtWidgets.QWidget(self.GroupBox_step2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 511, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.Layout_step2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.Layout_step2.setContentsMargins(0, 0, 0, 0)
        self.Layout_step2.setObjectName("Layout_step2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(88, 0))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Layout_step2_left = QtWidgets.QVBoxLayout()
        self.Layout_step2_left.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Layout_step2_left.setObjectName("Layout_step2_left")
        self.Label_alpha = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_alpha.setFont(font)
        self.Label_alpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_alpha.setObjectName("Label_alpha")
        self.Layout_step2_left.addWidget(self.Label_alpha)
        self.Label_beta = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_beta.setFont(font)
        self.Label_beta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_beta.setObjectName("Label_beta")
        self.Layout_step2_left.addWidget(self.Label_beta)
        self.Label_tau = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_tau.setFont(font)
        self.Label_tau.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_tau.setObjectName("Label_tau")
        self.Layout_step2_left.addWidget(self.Label_tau)
        self.Label_epsiloninf = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_epsiloninf.setFont(font)
        self.Label_epsiloninf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_epsiloninf.setObjectName("Label_epsiloninf")
        self.Layout_step2_left.addWidget(self.Label_epsiloninf)
        self.Label_deltaepsilon = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_deltaepsilon.setFont(font)
        self.Label_deltaepsilon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_deltaepsilon.setObjectName("Label_deltaepsilon")
        self.Layout_step2_left.addWidget(self.Label_deltaepsilon)
        self.verticalLayout.addLayout(self.Layout_step2_left)
        self.Layout_step2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_4)
        self.Layout_step2_right = QtWidgets.QFormLayout()
        self.Layout_step2_right.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.Layout_step2_right.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.Layout_step2_right.setObjectName("Layout_step2_right")
        self.lcdNumber_alpha = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_alpha.setFont(font)
        self.lcdNumber_alpha.setSmallDecimalPoint(False)
        self.lcdNumber_alpha.setDigitCount(7)
        self.lcdNumber_alpha.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_alpha.setProperty("value", 1.0)
        self.lcdNumber_alpha.setProperty("intValue", 1)
        self.lcdNumber_alpha.setObjectName("lcdNumber_alpha")
        self.Layout_step2_right.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_alpha)
        self.lcdNumber_beta = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_beta.setFont(font)
        self.lcdNumber_beta.setDigitCount(7)
        self.lcdNumber_beta.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_beta.setProperty("value", 1.0)
        self.lcdNumber_beta.setObjectName("lcdNumber_beta")
        self.Layout_step2_right.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_beta)
        self.Slider_beta = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_beta.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_beta.setMaximum(100)
        self.Slider_beta.setSingleStep(1)
        self.Slider_beta.setPageStep(5)
        self.Slider_beta.setProperty("value", 100)
        self.Slider_beta.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_beta.setInvertedControls(False)
        self.Slider_beta.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_beta.setObjectName("Slider_beta")
        self.Layout_step2_right.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Slider_beta)
        self.lcdNumber_tau = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_tau.setFont(font)
        self.lcdNumber_tau.setSmallDecimalPoint(False)
        self.lcdNumber_tau.setDigitCount(7)
        self.lcdNumber_tau.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_tau.setProperty("value", 0.0)
        self.lcdNumber_tau.setObjectName("lcdNumber_tau")
        self.Layout_step2_right.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_tau)
        self.Slider_tau = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_tau.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_tau.setMinimum(0)
        self.Slider_tau.setMaximum(100)
        self.Slider_tau.setSingleStep(1)
        self.Slider_tau.setPageStep(2)
        self.Slider_tau.setProperty("value", 0)
        self.Slider_tau.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_tau.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_tau.setObjectName("Slider_tau")
        self.Layout_step2_right.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Slider_tau)
        self.lcdNumber_epsiloninf = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_epsiloninf.setFont(font)
        self.lcdNumber_epsiloninf.setDigitCount(7)
        self.lcdNumber_epsiloninf.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_epsiloninf.setObjectName("lcdNumber_epsiloninf")
        self.Layout_step2_right.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_epsiloninf)
        self.Slider_epsiloninf = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_epsiloninf.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_epsiloninf.setMaximum(100)
        self.Slider_epsiloninf.setPageStep(5)
        self.Slider_epsiloninf.setProperty("value", 0)
        self.Slider_epsiloninf.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_epsiloninf.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_epsiloninf.setObjectName("Slider_epsiloninf")
        self.Layout_step2_right.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Slider_epsiloninf)
        self.lcdNumber_deltaepsilon = QtWidgets.QLCDNumber(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_deltaepsilon.setFont(font)
        self.lcdNumber_deltaepsilon.setDigitCount(7)
        self.lcdNumber_deltaepsilon.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_deltaepsilon.setObjectName("lcdNumber_deltaepsilon")
        self.Layout_step2_right.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_deltaepsilon)
        self.Slider_deltaepsilon = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_deltaepsilon.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_deltaepsilon.setMaximum(100)
        self.Slider_deltaepsilon.setSingleStep(1)
        self.Slider_deltaepsilon.setPageStep(2)
        self.Slider_deltaepsilon.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_deltaepsilon.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_deltaepsilon.setObjectName("Slider_deltaepsilon")
        self.Layout_step2_right.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Slider_deltaepsilon)
        self.Slider_alpha = QtWidgets.QSlider(self.formLayoutWidget)
        self.Slider_alpha.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_alpha.setMaximum(100)
        self.Slider_alpha.setSingleStep(1)
        self.Slider_alpha.setPageStep(5)
        self.Slider_alpha.setProperty("value", 100)
        self.Slider_alpha.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_alpha.setInvertedControls(False)
        self.Slider_alpha.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_alpha.setObjectName("Slider_alpha")
        self.Layout_step2_right.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Slider_alpha)
        self.Layout_step2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.Layout_step2_right)
        self.GroupBox_step4 = QtWidgets.QGroupBox(self.tabDielectric)
        self.GroupBox_step4.setGeometry(QtCore.QRect(540, 210, 511, 431))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step4.setFont(font)
        self.GroupBox_step4.setAutoFillBackground(True)
        self.GroupBox_step4.setObjectName("GroupBox_step4")
        self.ListView_results = QtWidgets.QListView(self.GroupBox_step4)
        self.ListView_results.setGeometry(QtCore.QRect(10, 20, 491, 331))
        self.ListView_results.setObjectName("ListView_results")
        self.layoutWidget = QtWidgets.QWidget(self.GroupBox_step4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 360, 491, 68))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.CheckBox_reference = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.CheckBox_reference.setFont(font)
        self.CheckBox_reference.setObjectName("CheckBox_reference")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CheckBox_reference)
        self.ComboBox_reference = QtWidgets.QComboBox(self.layoutWidget)
        self.ComboBox_reference.setObjectName("ComboBox_reference")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_reference)
        self.CheckBox_All = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.CheckBox_All.setFont(font)
        self.CheckBox_All.setObjectName("CheckBox_All")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CheckBox_All)
        self.PushButton_plot = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_plot.setFont(font)
        self.PushButton_plot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_plot.setObjectName("PushButton_plot")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PushButton_plot)
        self.GroupBox_step1 = QtWidgets.QGroupBox(self.tabDielectric)
        self.GroupBox_step1.setGeometry(QtCore.QRect(10, 150, 521, 291))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step1.setFont(font)
        self.GroupBox_step1.setAutoFillBackground(True)
        self.GroupBox_step1.setObjectName("GroupBox_step1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.GroupBox_step1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 511, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Layout_step1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Layout_step1.setContentsMargins(0, 0, 0, 0)
        self.Layout_step1.setObjectName("Layout_step1")
        self.Layout_step1_file = QtWidgets.QHBoxLayout()
        self.Layout_step1_file.setObjectName("Layout_step1_file")
        self.PushButton_file = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_file.setFont(font)
        self.PushButton_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_file.setObjectName("PushButton_file")
        self.Layout_step1_file.addWidget(self.PushButton_file)
        self.PushButton_dir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_dir.setFont(font)
        self.PushButton_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_dir.setObjectName("PushButton_dir")
        self.Layout_step1_file.addWidget(self.PushButton_dir)
        self.Layout_step1.addLayout(self.Layout_step1_file)
        self.ListView_file = QtWidgets.QListView(self.verticalLayoutWidget)
        self.ListView_file.setObjectName("ListView_file")
        self.Layout_step1.addWidget(self.ListView_file)
        self.Label_step1_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Label_step1_1.setObjectName("Label_step1_1")
        self.Layout_step1.addWidget(self.Label_step1_1)
        self.Label_step1_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Label_step1_2.setObjectName("Label_step1_2")
        self.Layout_step1.addWidget(self.Label_step1_2)
        self.GroupBox_title = QtWidgets.QGroupBox(self.tabDielectric)
        self.GroupBox_title.setGeometry(QtCore.QRect(10, 0, 1041, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_title.sizePolicy().hasHeightForWidth())
        self.GroupBox_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_title.setFont(font)
        self.GroupBox_title.setStyleSheet("")
        self.GroupBox_title.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupBox_title.setObjectName("GroupBox_title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.GroupBox_title)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 1021, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Layout_title = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Layout_title.setContentsMargins(0, 0, 0, 0)
        self.Layout_title.setObjectName("Layout_title")
        self.Label_fomula = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Label_fomula.setStyleSheet("image: url(:/Formula/source/formula.png);")
        self.Label_fomula.setText("")
        self.Label_fomula.setObjectName("Label_fomula")
        self.Layout_title.addWidget(self.Label_fomula)
        self.Layout_title_right = QtWidgets.QGridLayout()
        self.Layout_title_right.setObjectName("Layout_title_right")
        self.RadioButton_ccmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_ccmodel.setObjectName("RadioButton_ccmodel")
        self.Layout_title_right.addWidget(self.RadioButton_ccmodel, 1, 0, 1, 1)
        self.RadioButton_hnmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_hnmodel.setChecked(True)
        self.RadioButton_hnmodel.setObjectName("RadioButton_hnmodel")
        self.Layout_title_right.addWidget(self.RadioButton_hnmodel, 0, 0, 1, 1)
        self.RadioButton_cdmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_cdmodel.setObjectName("RadioButton_cdmodel")
        self.Layout_title_right.addWidget(self.RadioButton_cdmodel, 0, 1, 1, 1)
        self.RadioButton_dmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_dmodel.setObjectName("RadioButton_dmodel")
        self.Layout_title_right.addWidget(self.RadioButton_dmodel, 1, 1, 1, 1)
        self.Layout_title.addLayout(self.Layout_title_right)
        self.tabs.addTab(self.tabDielectric, "")
        self.tabMagnetization = QtWidgets.QWidget()
        self.tabMagnetization.setObjectName("tabMagnetization")
        self.GroupBox_title_2 = QtWidgets.QGroupBox(self.tabMagnetization)
        self.GroupBox_title_2.setGeometry(QtCore.QRect(10, 0, 1041, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_title_2.sizePolicy().hasHeightForWidth())
        self.GroupBox_title_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_title_2.setFont(font)
        self.GroupBox_title_2.setStyleSheet("")
        self.GroupBox_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupBox_title_2.setObjectName("GroupBox_title_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.GroupBox_title_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 30, 1021, 66))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.Layout_title_M = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.Layout_title_M.setContentsMargins(0, 0, 0, 0)
        self.Layout_title_M.setObjectName("Layout_title_M")
        self.Label_fomula_M = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Label_fomula_M.setStyleSheet("image: url(:/Formula/source/formula_m.png)")
        self.Label_fomula_M.setText("")
        self.Label_fomula_M.setObjectName("Label_fomula_M")
        self.Layout_title_M.addWidget(self.Label_fomula_M)
        self.Layout_title_right_M = QtWidgets.QGridLayout()
        self.Layout_title_right_M.setObjectName("Layout_title_right_M")
        self.RadioButton_tamodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.RadioButton_tamodel.setObjectName("RadioButton_tamodel")
        self.Layout_title_right_M.addWidget(self.RadioButton_tamodel, 1, 1, 1, 1)
        self.RadioButton_jamodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.RadioButton_jamodel.setChecked(True)
        self.RadioButton_jamodel.setObjectName("RadioButton_jamodel")
        self.Layout_title_right_M.addWidget(self.RadioButton_jamodel, 0, 0, 1, 1)
        self.RadioButton_brmodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.RadioButton_brmodel.setObjectName("RadioButton_brmodel")
        self.Layout_title_right_M.addWidget(self.RadioButton_brmodel, 0, 1, 1, 1)
        self.RadioButton_lamodel = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.RadioButton_lamodel.setObjectName("RadioButton_lamodel")
        self.Layout_title_right_M.addWidget(self.RadioButton_lamodel, 1, 0, 1, 1)
        self.Layout_title_M.addLayout(self.Layout_title_right_M)
        self.GroupBox_step1_M = QtWidgets.QGroupBox(self.tabMagnetization)
        self.GroupBox_step1_M.setGeometry(QtCore.QRect(10, 110, 521, 291))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step1_M.setFont(font)
        self.GroupBox_step1_M.setAutoFillBackground(True)
        self.GroupBox_step1_M.setObjectName("GroupBox_step1_M")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.GroupBox_step1_M)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 511, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Layout_step1_M = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Layout_step1_M.setContentsMargins(0, 0, 0, 0)
        self.Layout_step1_M.setObjectName("Layout_step1_M")
        self.Layout_step1_file_M = QtWidgets.QHBoxLayout()
        self.Layout_step1_file_M.setObjectName("Layout_step1_file_M")
        self.PushButton_file_M = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_file_M.setFont(font)
        self.PushButton_file_M.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_file_M.setObjectName("PushButton_file_M")
        self.Layout_step1_file_M.addWidget(self.PushButton_file_M)
        self.PushButton_dir_M = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_dir_M.setFont(font)
        self.PushButton_dir_M.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_dir_M.setObjectName("PushButton_dir_M")
        self.Layout_step1_file_M.addWidget(self.PushButton_dir_M)
        self.Layout_step1_M.addLayout(self.Layout_step1_file_M)
        self.ListView_file_M = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.ListView_file_M.setObjectName("ListView_file_M")
        self.Layout_step1_M.addWidget(self.ListView_file_M)
        self.Layout_unit_M = QtWidgets.QHBoxLayout()
        self.Layout_unit_M.setObjectName("Layout_unit_M")
        self.Layout_unit_M_unit_M = QtWidgets.QFormLayout()
        self.Layout_unit_M_unit_M.setObjectName("Layout_unit_M_unit_M")
        self.Label_unit_M = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_unit_M.setFont(font)
        self.Label_unit_M.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_unit_M.setObjectName("Label_unit_M")
        self.Layout_unit_M_unit_M.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_unit_M)
        self.ComboBox_unit_M = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.ComboBox_unit_M.setObjectName("ComboBox_unit_M")
        self.Layout_unit_M_unit_M.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_unit_M)
        self.Layout_unit_M.addLayout(self.Layout_unit_M_unit_M)
        self.Layout_unit_M_unit_H = QtWidgets.QFormLayout()
        self.Layout_unit_M_unit_H.setObjectName("Layout_unit_M_unit_H")
        self.Label_unit_H = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_unit_H.setFont(font)
        self.Label_unit_H.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_unit_H.setObjectName("Label_unit_H")
        self.Layout_unit_M_unit_H.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_unit_H)
        self.ComboBox_unit_H = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.ComboBox_unit_H.setObjectName("ComboBox_unit_H")
        self.Layout_unit_M_unit_H.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_unit_H)
        self.Layout_unit_M.addLayout(self.Layout_unit_M_unit_H)
        self.Layout_step1_M.addLayout(self.Layout_unit_M)
        self.Label_step1_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Label_step1_3.setObjectName("Label_step1_3")
        self.Layout_step1_M.addWidget(self.Label_step1_3)
        self.GroupBox_step2_M = QtWidgets.QGroupBox(self.tabMagnetization)
        self.GroupBox_step2_M.setGeometry(QtCore.QRect(10, 410, 521, 231))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step2_M.setFont(font)
        self.GroupBox_step2_M.setAutoFillBackground(True)
        self.GroupBox_step2_M.setObjectName("GroupBox_step2_M")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.GroupBox_step2_M)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 511, 201))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.Layout_step2_M = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.Layout_step2_M.setContentsMargins(0, 0, 0, 0)
        self.Layout_step2_M.setObjectName("Layout_step2_M")
        self.groupBox_5 = QtWidgets.QGroupBox(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(88, 0))
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Layout_step2_M_left = QtWidgets.QVBoxLayout()
        self.Layout_step2_M_left.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Layout_step2_M_left.setObjectName("Layout_step2_M_left")
        self.Label_ms = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_ms.setFont(font)
        self.Label_ms.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_ms.setObjectName("Label_ms")
        self.Layout_step2_M_left.addWidget(self.Label_ms)
        self.Label_a = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_a.setFont(font)
        self.Label_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_a.setObjectName("Label_a")
        self.Layout_step2_M_left.addWidget(self.Label_a)
        self.Label_alpha_2 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_alpha_2.setFont(font)
        self.Label_alpha_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_alpha_2.setObjectName("Label_alpha_2")
        self.Layout_step2_M_left.addWidget(self.Label_alpha_2)
        self.Label_c = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_c.setFont(font)
        self.Label_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_c.setObjectName("Label_c")
        self.Layout_step2_M_left.addWidget(self.Label_c)
        self.Label_J = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_J.setFont(font)
        self.Label_J.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_J.setObjectName("Label_J")
        self.Layout_step2_M_left.addWidget(self.Label_J)
        self.Label_g_J = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_g_J.setFont(font)
        self.Label_g_J.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_g_J.setObjectName("Label_g_J")
        self.Layout_step2_M_left.addWidget(self.Label_g_J)
        self.verticalLayout_3.addLayout(self.Layout_step2_M_left)
        self.Layout_step2_M.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_5)
        self.Layout_step2_M_right = QtWidgets.QFormLayout()
        self.Layout_step2_M_right.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.Layout_step2_M_right.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.Layout_step2_M_right.setObjectName("Layout_step2_M_right")
        self.lcdNumber_ms = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_ms.setFont(font)
        self.lcdNumber_ms.setSmallDecimalPoint(False)
        self.lcdNumber_ms.setDigitCount(7)
        self.lcdNumber_ms.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_ms.setProperty("value", 1.0)
        self.lcdNumber_ms.setProperty("intValue", 1)
        self.lcdNumber_ms.setObjectName("lcdNumber_ms")
        self.Layout_step2_M_right.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_ms)
        self.Slider_ms = QtWidgets.QSlider(self.formLayoutWidget_3)
        self.Slider_ms.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_ms.setMaximum(100)
        self.Slider_ms.setSingleStep(1)
        self.Slider_ms.setPageStep(5)
        self.Slider_ms.setProperty("value", 100)
        self.Slider_ms.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_ms.setInvertedControls(False)
        self.Slider_ms.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_ms.setObjectName("Slider_ms")
        self.Layout_step2_M_right.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Slider_ms)
        self.lcdNumber_a = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_a.setFont(font)
        self.lcdNumber_a.setDigitCount(7)
        self.lcdNumber_a.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_a.setProperty("value", 1.0)
        self.lcdNumber_a.setObjectName("lcdNumber_a")
        self.Layout_step2_M_right.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_a)
        self.Slider_a = QtWidgets.QSlider(self.formLayoutWidget_3)
        self.Slider_a.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_a.setMaximum(100)
        self.Slider_a.setSingleStep(1)
        self.Slider_a.setPageStep(5)
        self.Slider_a.setProperty("value", 100)
        self.Slider_a.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_a.setInvertedControls(False)
        self.Slider_a.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_a.setObjectName("Slider_a")
        self.Layout_step2_M_right.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Slider_a)
        self.lcdNumber_alpha_2 = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_alpha_2.setFont(font)
        self.lcdNumber_alpha_2.setSmallDecimalPoint(False)
        self.lcdNumber_alpha_2.setDigitCount(7)
        self.lcdNumber_alpha_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_alpha_2.setProperty("value", 0.0)
        self.lcdNumber_alpha_2.setObjectName("lcdNumber_alpha_2")
        self.Layout_step2_M_right.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_alpha_2)
        self.Slider_alpha_2 = QtWidgets.QSlider(self.formLayoutWidget_3)
        self.Slider_alpha_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_alpha_2.setMinimum(0)
        self.Slider_alpha_2.setMaximum(100)
        self.Slider_alpha_2.setSingleStep(1)
        self.Slider_alpha_2.setPageStep(2)
        self.Slider_alpha_2.setProperty("value", 0)
        self.Slider_alpha_2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_alpha_2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_alpha_2.setObjectName("Slider_alpha_2")
        self.Layout_step2_M_right.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Slider_alpha_2)
        self.lcdNumber_c = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_c.setFont(font)
        self.lcdNumber_c.setDigitCount(7)
        self.lcdNumber_c.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_c.setObjectName("lcdNumber_c")
        self.Layout_step2_M_right.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_c)
        self.Slider_c = QtWidgets.QSlider(self.formLayoutWidget_3)
        self.Slider_c.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_c.setMaximum(100)
        self.Slider_c.setPageStep(5)
        self.Slider_c.setProperty("value", 0)
        self.Slider_c.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_c.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_c.setObjectName("Slider_c")
        self.Layout_step2_M_right.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Slider_c)
        self.lcdNumber_J = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_J.setFont(font)
        self.lcdNumber_J.setDigitCount(7)
        self.lcdNumber_J.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_J.setObjectName("lcdNumber_J")
        self.Layout_step2_M_right.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_J)
        self.Slider_J = QtWidgets.QSlider(self.formLayoutWidget_3)
        self.Slider_J.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_J.setMaximum(100)
        self.Slider_J.setSingleStep(1)
        self.Slider_J.setPageStep(2)
        self.Slider_J.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_J.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_J.setObjectName("Slider_J")
        self.Layout_step2_M_right.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Slider_J)
        self.lcdNumber_g_J = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_g_J.setFont(font)
        self.lcdNumber_g_J.setDigitCount(7)
        self.lcdNumber_g_J.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_g_J.setObjectName("lcdNumber_g_J")
        self.Layout_step2_M_right.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_g_J)
        self.Slider_g_J = QtWidgets.QSlider(self.formLayoutWidget_3)
        self.Slider_g_J.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_g_J.setMaximum(100)
        self.Slider_g_J.setSingleStep(1)
        self.Slider_g_J.setPageStep(2)
        self.Slider_g_J.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_g_J.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_g_J.setObjectName("Slider_g_J")
        self.Layout_step2_M_right.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Slider_g_J)
        self.Layout_step2_M.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.Layout_step2_M_right)
        self.GroupBox_step4_M = QtWidgets.QGroupBox(self.tabMagnetization)
        self.GroupBox_step4_M.setGeometry(QtCore.QRect(540, 170, 511, 471))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step4_M.setFont(font)
        self.GroupBox_step4_M.setAutoFillBackground(True)
        self.GroupBox_step4_M.setObjectName("GroupBox_step4_M")
        self.ListView_results_M = QtWidgets.QListView(self.GroupBox_step4_M)
        self.ListView_results_M.setGeometry(QtCore.QRect(10, 20, 491, 361))
        self.ListView_results_M.setObjectName("ListView_results_M")
        self.layoutWidget_2 = QtWidgets.QWidget(self.GroupBox_step4_M)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 390, 491, 68))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_M = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_M.setContentsMargins(0, 0, 0, 0)
        self.formLayout_M.setObjectName("formLayout_M")
        self.CheckBox_bg = QtWidgets.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.CheckBox_bg.setFont(font)
        self.CheckBox_bg.setObjectName("CheckBox_bg")
        self.formLayout_M.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CheckBox_bg)
        self.ComboBox_bg = QtWidgets.QComboBox(self.layoutWidget_2)
        self.ComboBox_bg.setObjectName("ComboBox_bg")
        self.formLayout_M.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_bg)
        self.CheckBox_All_M = QtWidgets.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.CheckBox_All_M.setFont(font)
        self.CheckBox_All_M.setObjectName("CheckBox_All_M")
        self.formLayout_M.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CheckBox_All_M)
        self.PushButton_plot_M = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_plot_M.setFont(font)
        self.PushButton_plot_M.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_plot_M.setObjectName("PushButton_plot_M")
        self.formLayout_M.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PushButton_plot_M)
        self.PushButton_simulate_M = QtWidgets.QPushButton(self.tabMagnetization)
        self.PushButton_simulate_M.setGeometry(QtCore.QRect(540, 120, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_simulate_M.setFont(font)
        self.PushButton_simulate_M.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_simulate_M.setAutoDefault(False)
        self.PushButton_simulate_M.setDefault(False)
        self.PushButton_simulate_M.setFlat(False)
        self.PushButton_simulate_M.setObjectName("PushButton_simulate_M")
        self.tabs.addTab(self.tabMagnetization, "")
        self.tabFaraday = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(15)
        self.tabFaraday.setFont(font)
        self.tabFaraday.setObjectName("tabFaraday")
        self.GroupBox_title_F = QtWidgets.QGroupBox(self.tabFaraday)
        self.GroupBox_title_F.setGeometry(QtCore.QRect(10, 0, 1041, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_title_F.sizePolicy().hasHeightForWidth())
        self.GroupBox_title_F.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_title_F.setFont(font)
        self.GroupBox_title_F.setStyleSheet("")
        self.GroupBox_title_F.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupBox_title_F.setObjectName("GroupBox_title_F")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.GroupBox_title_F)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(9, 30, 1021, 66))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.Layout_title_F = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.Layout_title_F.setContentsMargins(0, 0, 0, 0)
        self.Layout_title_F.setObjectName("Layout_title_F")
        self.Label_fomula_F = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.Label_fomula_F.setStyleSheet("image: url(:/Formula/source/formula_faraday.png)")
        self.Label_fomula_F.setText("")
        self.Label_fomula_F.setObjectName("Label_fomula_F")
        self.Layout_title_F.addWidget(self.Label_fomula_F)
        self.Layout_title_right_F = QtWidgets.QGridLayout()
        self.Layout_title_right_F.setObjectName("Layout_title_right_F")
        self.RadioButton_camodel_2nd = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.RadioButton_camodel_2nd.setObjectName("RadioButton_camodel_2nd")
        self.Layout_title_right_F.addWidget(self.RadioButton_camodel_2nd, 1, 1, 1, 1)
        self.RadioButton_camodel_1st = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.RadioButton_camodel_1st.setChecked(False)
        self.RadioButton_camodel_1st.setObjectName("RadioButton_camodel_1st")
        self.Layout_title_right_F.addWidget(self.RadioButton_camodel_1st, 1, 0, 1, 1)
        self.RadioButton_semodel_2nd = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.RadioButton_semodel_2nd.setChecked(True)
        self.RadioButton_semodel_2nd.setObjectName("RadioButton_semodel_2nd")
        self.Layout_title_right_F.addWidget(self.RadioButton_semodel_2nd, 0, 0, 1, 1)
        self.RadioButton_semodel_3rd = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.RadioButton_semodel_3rd.setObjectName("RadioButton_semodel_3rd")
        self.Layout_title_right_F.addWidget(self.RadioButton_semodel_3rd, 0, 1, 1, 1)
        self.Layout_title_F.addLayout(self.Layout_title_right_F)
        self.GroupBox_step1_F = QtWidgets.QGroupBox(self.tabFaraday)
        self.GroupBox_step1_F.setGeometry(QtCore.QRect(10, 110, 521, 291))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step1_F.setFont(font)
        self.GroupBox_step1_F.setAutoFillBackground(True)
        self.GroupBox_step1_F.setObjectName("GroupBox_step1_F")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.GroupBox_step1_F)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 511, 261))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.Layout_step1_F = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.Layout_step1_F.setContentsMargins(0, 0, 0, 0)
        self.Layout_step1_F.setObjectName("Layout_step1_F")
        self.Layout_step1_file_F = QtWidgets.QHBoxLayout()
        self.Layout_step1_file_F.setObjectName("Layout_step1_file_F")
        self.PushButton_file_F = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_file_F.setFont(font)
        self.PushButton_file_F.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_file_F.setObjectName("PushButton_file_F")
        self.Layout_step1_file_F.addWidget(self.PushButton_file_F)
        self.PushButton_dir_F = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_dir_F.setFont(font)
        self.PushButton_dir_F.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_dir_F.setObjectName("PushButton_dir_F")
        self.Layout_step1_file_F.addWidget(self.PushButton_dir_F)
        self.Layout_step1_F.addLayout(self.Layout_step1_file_F)
        self.ListView_file_F = QtWidgets.QListView(self.verticalLayoutWidget_5)
        self.ListView_file_F.setObjectName("ListView_file_F")
        self.Layout_step1_F.addWidget(self.ListView_file_F)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_unit_H_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_unit_H_3.setFont(font)
        self.Label_unit_H_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_unit_H_3.setObjectName("Label_unit_H_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_unit_H_3)
        self.ComboBox_unit_H_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.ComboBox_unit_H_3.setObjectName("ComboBox_unit_H_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_unit_H_3)
        self.Layout_step1_F.addLayout(self.formLayout_3)
        self.GroupBox_step2_F = QtWidgets.QGroupBox(self.tabFaraday)
        self.GroupBox_step2_F.setGeometry(QtCore.QRect(10, 410, 521, 231))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step2_F.setFont(font)
        self.GroupBox_step2_F.setAutoFillBackground(True)
        self.GroupBox_step2_F.setObjectName("GroupBox_step2_F")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.GroupBox_step2_F)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 511, 201))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.Layout_step2_F = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.Layout_step2_F.setContentsMargins(0, 0, 0, 0)
        self.Layout_step2_F.setObjectName("Layout_step2_F")
        self.groupBox_8 = QtWidgets.QGroupBox(self.formLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(88, 0))
        self.groupBox_8.setAutoFillBackground(False)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setCheckable(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Layout_step2_M_left_3 = QtWidgets.QVBoxLayout()
        self.Layout_step2_M_left_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Layout_step2_M_left_3.setObjectName("Layout_step2_M_left_3")
        self.Label_alpha_3 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_alpha_3.setFont(font)
        self.Label_alpha_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_alpha_3.setObjectName("Label_alpha_3")
        self.Layout_step2_M_left_3.addWidget(self.Label_alpha_3)
        self.Label_A = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_A.setFont(font)
        self.Label_A.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_A.setObjectName("Label_A")
        self.Layout_step2_M_left_3.addWidget(self.Label_A)
        self.Label_B1 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_B1.setFont(font)
        self.Label_B1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_B1.setObjectName("Label_B1")
        self.Layout_step2_M_left_3.addWidget(self.Label_B1)
        self.Label_B2 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_B2.setFont(font)
        self.Label_B2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_B2.setObjectName("Label_B2")
        self.Layout_step2_M_left_3.addWidget(self.Label_B2)
        self.Label_C1 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_C1.setFont(font)
        self.Label_C1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_C1.setObjectName("Label_C1")
        self.Layout_step2_M_left_3.addWidget(self.Label_C1)
        self.Label_C2 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label_C2.setFont(font)
        self.Label_C2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_C2.setObjectName("Label_C2")
        self.Layout_step2_M_left_3.addWidget(self.Label_C2)
        self.verticalLayout_5.addLayout(self.Layout_step2_M_left_3)
        self.Layout_step2_F.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_8)
        self.Layout_step2_F_right = QtWidgets.QFormLayout()
        self.Layout_step2_F_right.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.Layout_step2_F_right.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.Layout_step2_F_right.setObjectName("Layout_step2_F_right")
        self.lcdNumber_ms_3 = QtWidgets.QLCDNumber(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_ms_3.setFont(font)
        self.lcdNumber_ms_3.setSmallDecimalPoint(False)
        self.lcdNumber_ms_3.setDigitCount(7)
        self.lcdNumber_ms_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_ms_3.setProperty("value", 1.0)
        self.lcdNumber_ms_3.setProperty("intValue", 1)
        self.lcdNumber_ms_3.setObjectName("lcdNumber_ms_3")
        self.Layout_step2_F_right.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_ms_3)
        self.Slider_ms_3 = QtWidgets.QSlider(self.formLayoutWidget_8)
        self.Slider_ms_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_ms_3.setMaximum(100)
        self.Slider_ms_3.setSingleStep(1)
        self.Slider_ms_3.setPageStep(5)
        self.Slider_ms_3.setProperty("value", 100)
        self.Slider_ms_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_ms_3.setInvertedControls(False)
        self.Slider_ms_3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_ms_3.setObjectName("Slider_ms_3")
        self.Layout_step2_F_right.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Slider_ms_3)
        self.lcdNumber_a_3 = QtWidgets.QLCDNumber(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_a_3.setFont(font)
        self.lcdNumber_a_3.setDigitCount(7)
        self.lcdNumber_a_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_a_3.setProperty("value", 1.0)
        self.lcdNumber_a_3.setObjectName("lcdNumber_a_3")
        self.Layout_step2_F_right.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_a_3)
        self.Slider_a_3 = QtWidgets.QSlider(self.formLayoutWidget_8)
        self.Slider_a_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_a_3.setMaximum(100)
        self.Slider_a_3.setSingleStep(1)
        self.Slider_a_3.setPageStep(5)
        self.Slider_a_3.setProperty("value", 100)
        self.Slider_a_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_a_3.setInvertedControls(False)
        self.Slider_a_3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_a_3.setObjectName("Slider_a_3")
        self.Layout_step2_F_right.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Slider_a_3)
        self.lcdNumber_alpha_5 = QtWidgets.QLCDNumber(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_alpha_5.setFont(font)
        self.lcdNumber_alpha_5.setSmallDecimalPoint(False)
        self.lcdNumber_alpha_5.setDigitCount(7)
        self.lcdNumber_alpha_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_alpha_5.setProperty("value", 0.0)
        self.lcdNumber_alpha_5.setObjectName("lcdNumber_alpha_5")
        self.Layout_step2_F_right.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_alpha_5)
        self.Slider_alpha_5 = QtWidgets.QSlider(self.formLayoutWidget_8)
        self.Slider_alpha_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_alpha_5.setMinimum(0)
        self.Slider_alpha_5.setMaximum(100)
        self.Slider_alpha_5.setSingleStep(1)
        self.Slider_alpha_5.setPageStep(2)
        self.Slider_alpha_5.setProperty("value", 0)
        self.Slider_alpha_5.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_alpha_5.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_alpha_5.setObjectName("Slider_alpha_5")
        self.Layout_step2_F_right.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Slider_alpha_5)
        self.lcdNumber_c_3 = QtWidgets.QLCDNumber(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_c_3.setFont(font)
        self.lcdNumber_c_3.setDigitCount(7)
        self.lcdNumber_c_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_c_3.setObjectName("lcdNumber_c_3")
        self.Layout_step2_F_right.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_c_3)
        self.Slider_c_3 = QtWidgets.QSlider(self.formLayoutWidget_8)
        self.Slider_c_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_c_3.setMaximum(100)
        self.Slider_c_3.setPageStep(5)
        self.Slider_c_3.setProperty("value", 0)
        self.Slider_c_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_c_3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_c_3.setObjectName("Slider_c_3")
        self.Layout_step2_F_right.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Slider_c_3)
        self.lcdNumber_J_3 = QtWidgets.QLCDNumber(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_J_3.setFont(font)
        self.lcdNumber_J_3.setDigitCount(7)
        self.lcdNumber_J_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_J_3.setObjectName("lcdNumber_J_3")
        self.Layout_step2_F_right.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_J_3)
        self.Slider_J_3 = QtWidgets.QSlider(self.formLayoutWidget_8)
        self.Slider_J_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_J_3.setMaximum(100)
        self.Slider_J_3.setSingleStep(1)
        self.Slider_J_3.setPageStep(2)
        self.Slider_J_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_J_3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_J_3.setObjectName("Slider_J_3")
        self.Layout_step2_F_right.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Slider_J_3)
        self.lcdNumber_g_J_3 = QtWidgets.QLCDNumber(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_g_J_3.setFont(font)
        self.lcdNumber_g_J_3.setDigitCount(7)
        self.lcdNumber_g_J_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_g_J_3.setObjectName("lcdNumber_g_J_3")
        self.Layout_step2_F_right.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lcdNumber_g_J_3)
        self.Slider_g_J_3 = QtWidgets.QSlider(self.formLayoutWidget_8)
        self.Slider_g_J_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_g_J_3.setMaximum(100)
        self.Slider_g_J_3.setSingleStep(1)
        self.Slider_g_J_3.setPageStep(2)
        self.Slider_g_J_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_g_J_3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_g_J_3.setObjectName("Slider_g_J_3")
        self.Layout_step2_F_right.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Slider_g_J_3)
        self.Layout_step2_F.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.Layout_step2_F_right)
        self.PushButton_simulate_F = QtWidgets.QPushButton(self.tabFaraday)
        self.PushButton_simulate_F.setGeometry(QtCore.QRect(540, 120, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_simulate_F.setFont(font)
        self.PushButton_simulate_F.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_simulate_F.setAutoDefault(False)
        self.PushButton_simulate_F.setDefault(False)
        self.PushButton_simulate_F.setFlat(False)
        self.PushButton_simulate_F.setObjectName("PushButton_simulate_F")
        self.GroupBox_step4_F = QtWidgets.QGroupBox(self.tabFaraday)
        self.GroupBox_step4_F.setGeometry(QtCore.QRect(540, 170, 511, 471))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GroupBox_step4_F.setFont(font)
        self.GroupBox_step4_F.setAutoFillBackground(True)
        self.GroupBox_step4_F.setObjectName("GroupBox_step4_F")
        self.ListView_results_F = QtWidgets.QListView(self.GroupBox_step4_F)
        self.ListView_results_F.setGeometry(QtCore.QRect(10, 20, 491, 401))
        self.ListView_results_F.setObjectName("ListView_results_F")
        self.layoutWidget_3 = QtWidgets.QWidget(self.GroupBox_step4_F)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 427, 491, 34))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.formLayout_F = QtWidgets.QFormLayout(self.layoutWidget_3)
        self.formLayout_F.setContentsMargins(0, 0, 0, 0)
        self.formLayout_F.setObjectName("formLayout_F")
        self.CheckBox_All_F = QtWidgets.QCheckBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.CheckBox_All_F.setFont(font)
        self.CheckBox_All_F.setObjectName("CheckBox_All_F")
        self.formLayout_F.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CheckBox_All_F)
        self.PushButton_plot_F = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.PushButton_plot_F.setFont(font)
        self.PushButton_plot_F.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_plot_F.setObjectName("PushButton_plot_F")
        self.formLayout_F.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PushButton_plot_F)
        self.tabs.addTab(self.tabFaraday, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSaveResultsAs = QtWidgets.QAction(MainWindow)
        self.actionSaveResultsAs.setObjectName("actionSaveResultsAs")
        self.actionParameters_Range = QtWidgets.QAction(MainWindow)
        self.actionParameters_Range.setObjectName("actionParameters_Range")
        self.menuFile.addAction(self.actionSaveResultsAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionParameters_Range)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.RadioButton_hnmodel, self.RadioButton_ccmodel)
        MainWindow.setTabOrder(self.RadioButton_ccmodel, self.RadioButton_cdmodel)
        MainWindow.setTabOrder(self.RadioButton_cdmodel, self.RadioButton_dmodel)
        MainWindow.setTabOrder(self.RadioButton_dmodel, self.PushButton_file)
        MainWindow.setTabOrder(self.PushButton_file, self.PushButton_dir)
        MainWindow.setTabOrder(self.PushButton_dir, self.ListView_file)
        MainWindow.setTabOrder(self.ListView_file, self.Slider_alpha)
        MainWindow.setTabOrder(self.Slider_alpha, self.Slider_beta)
        MainWindow.setTabOrder(self.Slider_beta, self.Slider_tau)
        MainWindow.setTabOrder(self.Slider_tau, self.Slider_epsiloninf)
        MainWindow.setTabOrder(self.Slider_epsiloninf, self.Slider_deltaepsilon)
        MainWindow.setTabOrder(self.Slider_deltaepsilon, self.PushButton_simulate)
        MainWindow.setTabOrder(self.PushButton_simulate, self.ListView_results)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulator by Cheng WANG, Masumoto Lab."))
        self.PushButton_simulate.setText(_translate("MainWindow", "STEP.3 Simulate!!!"))
        self.GroupBox_step2.setTitle(_translate("MainWindow", "STEP.2 Parameters"))
        self.Label_alpha.setText(_translate("MainWindow", "Alpha: "))
        self.Label_beta.setText(_translate("MainWindow", "Beta: "))
        self.Label_tau.setText(_translate("MainWindow", "Tau: "))
        self.Label_epsiloninf.setText(_translate("MainWindow", "Epsilon_Inf: "))
        self.Label_deltaepsilon.setText(_translate("MainWindow", "Delta_Epsilon: "))
        self.GroupBox_step4.setTitle(_translate("MainWindow", "STEP.4 Results"))
        self.CheckBox_reference.setText(_translate("MainWindow", "Ref."))
        self.CheckBox_All.setText(_translate("MainWindow", "ALL"))
        self.PushButton_plot.setText(_translate("MainWindow", "Plot"))
        self.GroupBox_step1.setTitle(_translate("MainWindow", "STEP.1 Raw Data"))
        self.PushButton_file.setText(_translate("MainWindow", "File..."))
        self.PushButton_dir.setText(_translate("MainWindow", "Dir..."))
        self.Label_step1_1.setText(_translate("MainWindow", "*This should be the raw file from LCR meter."))
        self.Label_step1_2.setText(_translate("MainWindow", "**Filename: [serial](-DCB-[DCB]), eg. 88-8-DCB8.8"))
        self.GroupBox_title.setTitle(_translate("MainWindow", "Havriliak–Negami Relaxation"))
        self.RadioButton_ccmodel.setText(_translate("MainWindow", "Cole–Cole"))
        self.RadioButton_hnmodel.setText(_translate("MainWindow", "Havriliak–Negami"))
        self.RadioButton_cdmodel.setText(_translate("MainWindow", "Cole–Davidson"))
        self.RadioButton_dmodel.setText(_translate("MainWindow", "Debye"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabDielectric), _translate("MainWindow", "Dielectric Relaxation"))
        self.GroupBox_title_2.setTitle(_translate("MainWindow", "Jiles-Atherton Magnetization"))
        self.RadioButton_tamodel.setText(_translate("MainWindow", "Takacs"))
        self.RadioButton_jamodel.setText(_translate("MainWindow", "Jiles-Atherton"))
        self.RadioButton_brmodel.setText(_translate("MainWindow", "Brillouin"))
        self.RadioButton_lamodel.setText(_translate("MainWindow", "Langevin"))
        self.GroupBox_step1_M.setTitle(_translate("MainWindow", "STEP.1 Raw Data"))
        self.PushButton_file_M.setText(_translate("MainWindow", "File..."))
        self.PushButton_dir_M.setText(_translate("MainWindow", "Dir..."))
        self.Label_unit_M.setText(_translate("MainWindow", "M unit: "))
        self.Label_unit_H.setText(_translate("MainWindow", "H unit: "))
        self.Label_step1_3.setText(_translate("MainWindow", "*This should be the raw file from VSM device."))
        self.GroupBox_step2_M.setTitle(_translate("MainWindow", "STEP.2 Parameters"))
        self.Label_ms.setText(_translate("MainWindow", "sat. mz.: "))
        self.Label_a.setText(_translate("MainWindow", "a: "))
        self.Label_alpha_2.setText(_translate("MainWindow", "α: "))
        self.Label_c.setText(_translate("MainWindow", "c: "))
        self.Label_J.setText(_translate("MainWindow", "J: "))
        self.Label_g_J.setText(_translate("MainWindow", "g_J: "))
        self.GroupBox_step4_M.setTitle(_translate("MainWindow", "STEP.4 Results"))
        self.CheckBox_bg.setText(_translate("MainWindow", "Ref."))
        self.CheckBox_All_M.setText(_translate("MainWindow", "ALL"))
        self.PushButton_plot_M.setText(_translate("MainWindow", "Plot"))
        self.PushButton_simulate_M.setText(_translate("MainWindow", "STEP.3 Simulate!!!"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabMagnetization), _translate("MainWindow", "Magnetization"))
        self.GroupBox_title_F.setTitle(_translate("MainWindow", "Faraday Rotation Angle"))
        self.RadioButton_camodel_2nd.setText(_translate("MainWindow", "2nd Cauchy"))
        self.RadioButton_camodel_1st.setText(_translate("MainWindow", "1st Cauchy"))
        self.RadioButton_semodel_2nd.setText(_translate("MainWindow", "2nd Sellmeier"))
        self.RadioButton_semodel_3rd.setText(_translate("MainWindow", "3rd Sellmeier"))
        self.GroupBox_step1_F.setTitle(_translate("MainWindow", "STEP.1 Raw Data"))
        self.PushButton_file_F.setText(_translate("MainWindow", "File..."))
        self.PushButton_dir_F.setText(_translate("MainWindow", "Dir..."))
        self.Label_unit_H_3.setText(_translate("MainWindow", "H unit: "))
        self.GroupBox_step2_F.setTitle(_translate("MainWindow", "STEP.2 Parameters"))
        self.Label_alpha_3.setText(_translate("MainWindow", "α: "))
        self.Label_A.setText(_translate("MainWindow", "A: "))
        self.Label_B1.setText(_translate("MainWindow", "B1: "))
        self.Label_B2.setText(_translate("MainWindow", "B2: "))
        self.Label_C1.setText(_translate("MainWindow", "C1: "))
        self.Label_C2.setText(_translate("MainWindow", "C2: "))
        self.PushButton_simulate_F.setText(_translate("MainWindow", "STEP.3 Simulate!!!"))
        self.GroupBox_step4_F.setTitle(_translate("MainWindow", "STEP.4 Results"))
        self.CheckBox_All_F.setText(_translate("MainWindow", "ALL"))
        self.PushButton_plot_F.setText(_translate("MainWindow", "Plot"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabFaraday), _translate("MainWindow", "Faraday"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSaveResultsAs.setText(_translate("MainWindow", "Save Results As..."))
        self.actionParameters_Range.setText(_translate("MainWindow", "Parameters Range"))
import simulator_ui_rc
